name: MySQLWhitelist
main: me.steffansk1997.MySQLWhitelist.MySQLWhitelist
version: 1.3
description: >
             MySQLWhitelist
commands:
  mywl:
    alias: mywhitelist
permissions:
  MySQLWhitelist.*:
    description: Gives access to all MySQLWhitelist commands
    children:
      MySQLWhitelist.add: true
      MySQLWhitelist.del: true
      MySQLWhitelist.on: true
      MySQLWhitelist.off: true
  MySQLWhitelist.add:
    description: Allows you to add someone to the whitelist
    default: op
  MySQLWhitelist.del:
    description: Allows you to remove someone from the whitelist
    default: op
  MySQLWhitelist.on:
    description: Allows you to enable the whitelist
    default: op
  MySQLWhitelist.off:
    description: Allows you to disable the whitelist
    default: op